import { PerformancePresets, PerformanceTier } from './types';

export const PERFORMANCE_PRESETS: Record<PerformanceTier, PerformancePresets> = {
  ultra: {
    dpr: 2.5,
    particles: 5000,
    shadows: true,
    bloom: true,
    glassmorphism: true,
    motion: 'full',
    imageQuality: 'high',
    textureResolution: '4K',
    postProcessing: 'all',
    shaderComplexity: 'full',
  },
  quality: {
    dpr: 2,
    particles: 3000,
    shadows: true,
    bloom: true,
    glassmorphism: true,
    motion: 'full',
    imageQuality: 'high',
    textureResolution: '2K',
    postProcessing: 'all',
    shaderComplexity: 'full',
  },
  balanced: {
    dpr: 1,
    particles: 1500,
    shadows: true,
    bloom: false,
    glassmorphism: false,
    motion: 'medium',
    imageQuality: 'medium',
    textureResolution: '1K',
    postProcessing: 'limited',
    shaderComplexity: 'reduced',
  },
  performance: {
    dpr: 0.75,
    particles: 500,
    shadows: false,
    bloom: false,
    glassmorphism: false,
    motion: 'minimal',
    imageQuality: 'low',
    textureResolution: '512px',
    postProcessing: 'none',
    shaderComplexity: 'basic',
  },
};
